name: Angular MDC Test

on:
  push:
    branches:
      - master
      - '!gh-pages'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 13
      - run: yarn
      - run: yarn lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 13
      - run: yarn
      - name: Run unit tests
        run: yarn test
      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
  sass-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 13
      - run: yarn
      - name: Run Sass tests
        run: |
          yarn lint:css
